name: salert
description: Library for efficient sales amounts calculations, including discounts, subtotal before taxes, taxes and total amounts.
version: 0.0.6
repository: https://github.com/h4j4x/salert

environment:
  sdk: ^3.4.0

dev_dependencies:
  lints: ^4.0.0
  test: any
